version: '3.5'

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=cache
      - POSTGRES_HOST=db
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - database:/var/lib/postgresql/data
  cache:
    image: redis

volumes:
  database: